# Theano basics

## Expressions

In [13]:
# Import numpy
import numpy as np
# Import theano and theano.tensor
import theano, theano.tensor as T
# Import Lasagne floatX utility function for ensuring that data is of the correct type
from lasagne.utils import floatX

# Create some test data to play with
a = floatX(np.arange(10.0).reshape((2,5)))
b = floatX(np.arange(10.0,20.0).reshape((5,2)))

# Load the data into Theano as shared data (note the optional name parameter)
a_t = theano.shared(a, name='a')
b_t = theano.shared(b)

# Use the Theano equivalent of numpy.dot() to get the dot product
ab_t = T.dot(a_t, b_t)

# Evaluate to get the result
print(ab_t.eval())

[[ 160.  170.]
 [ 510.  545.]]


## Accessing and modifying shared data
Lets use `set_value` to change the values of the shared data and re-evaluate:

In [14]:
# Seeded random number generator
rng = np.random.RandomState(12345)

# Change the values of the shared data
a_t.set_value(floatX(rng.uniform(low=0, high=1, size=(2,5))))
b_t.set_value(floatX(rng.uniform(low=0, high=1, size=(5,2))))

# Print the new values then evaluate the previously built expression and print:
print(a_t.get_value())
print(b_t.get_value())
print(ab_t.eval())

[[ 0.92961609  0.31637555  0.18391882  0.20456028  0.567725  ]
 [ 0.5955447   0.96451449  0.65317708  0.74890661  0.65356988]]
[[ 0.74771482  0.96130675]
 [ 0.0083883   0.10644437]
 [ 0.2987037   0.65641117]
 [ 0.80981255  0.87217593]
 [ 0.96464759  0.72368532]]
[[ 1.46598887  1.63731575]
 [ 1.8854332   2.23007822]]


## Variables and functions

In [17]:
# Seeded random number generator
rng = np.random.RandomState(12345)

# Create a 2D variable; use the matrix constructor
x = T.matrix('x')

# Weights and biases of 5-channel input, 2-channel output
# linear model as shared data
W = theano.shared(floatX(rng.normal(0.25, size=(5,2))))
b = theano.shared(floatX(np.zeros((2,))))

# Linear model
linear = T.dot(x, W) + b

# Evaluation function
eval_linear = theano.function([x], linear)

# Test it:
test_data = floatX(rng.uniform(0, 1, (10,5)))
print(test_data)
print(eval_linear(test_data))

[[ 0.74771482  0.96130675  0.0083883   0.10644437  0.2987037 ]
 [ 0.65641117  0.80981255  0.87217593  0.96464759  0.72368532]
 [ 0.64247531  0.7174536   0.467599    0.32558468  0.4396446 ]
 [ 0.72968906  0.99401456  0.67687368  0.79082251  0.17091426]
 [ 0.02684928  0.80037022  0.90372252  0.02467621  0.49174732]
 [ 0.52625519  0.59636599  0.05195754  0.89508951  0.72826618]
 [ 0.81835002  0.50022274  0.81018943  0.09596852  0.21895005]
 [ 0.25871906  0.46810576  0.45937321  0.70950979  0.17805301]
 [ 0.53144991  0.16774222  0.76881391  0.92817056  0.60949367]
 [ 0.1501835   0.48962671  0.37734497  0.8486014   0.91109723]]
[[ 0.13432553  0.76851845]
 [ 2.81232309  3.2601366 ]
 [ 1.43153965  1.84846342]
 [ 1.71037173  2.01665854]
 [ 2.29757953  2.00904632]
 [ 1.02733076  1.85243356]
 [ 1.95351088  2.15374279]
 [ 1.32819879  1.44413781]
 [ 2.62176204  3.00520468]
 [ 1.93041217  2.39455056]]
